##############################################################################
#
# The MIT License (MIT)
# Copyright (c) 2017 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
# OR OTHER DEALINGS IN THE SOFTWARE.
#
##############################################################################

server:
    url: http://localhost/geocatalogo
    mimetype: application/xml; charset=UTF-8
    encoding: utf-8
    language: en-US
    pretty_print: true
    limit: 10

logging:
    level: NONE
    logfile: /tmp/geocatalogo.log

metadata:
    identification:
        title: geocatalogo
        abstract: Geospatial Catalogue in Go
        keywords:
            - geospatial
            - metadata
            - discovery
        keywords_type: theme
        fees: None
        accessconstraints: None
    provider:
        name: Organization Name
        url: https://github.com/tomkralidis/geocatalogo
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Hours of Service
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact

repository:
    type: bleve
    url: ./metadata-index.bleve
    mappings:
        identifier: identifier
        type: type
        last_modified: last_modified
        title : title
        abstract: abstract
        keywords: keywords
        geometry: bbox
